### ISSUE TITLE
Error running caffe model

### ISSUE THREAD

**Issue by ldjpr** [Prakashvanapalli/caffe_blogpost#1]
Hello

when running the model from the notebook I get the following error:

I0807 16:12:04.245479    76 caffe.cpp:211] Use CPU.
I0807 16:12:04.245878    76 solver.cpp:44] Initializing solver from parameters: 
test_iter: 100
test_interval: 500
base_lr: 0.001
display: 500
max_iter: 2000
lr_policy: "fixed"
momentum: 0.9
snapshot: 500
snapshot_prefix: "./snapshot/lenet_mnist"
solver_mode: CPU
net: "./train_val.prototxt"
train_state {
  level: 0
  stage: ""
}
momentum2: 0.999
type: "Adam"
I0807 16:12:04.246912    76 solver.cpp:87] Creating training net from net file: ./train_val.prototxt
I0807 16:12:04.247413    76 net.cpp:294] The NetState phase (0) differed from the phase (1) specified by a rule in layer mnist
I0807 16:12:04.247447    76 net.cpp:294] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I0807 16:12:04.247517    76 net.cpp:51] Initializing net from parameters: 
name: "LeNet"
state {
  phase: TRAIN
  level: 0
  stage: ""
}
layer {
  name: "mnist"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  hdf5_data_param {
    source: "./train_file_location.txt"
    batch_size: 100
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "pool2"
  top: "ip1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "ip1"
  top: "ip1"
}
layer {
  name: "ip2"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
}
I0807 16:12:04.247627    76 layer_factory.hpp:77] Creating layer mnist
I0807 16:12:04.247689    76 net.cpp:84] Creating Layer mnist
I0807 16:12:04.247714    76 net.cpp:380] mnist -> data
I0807 16:12:04.247736    76 net.cpp:380] mnist -> label
I0807 16:12:04.247750    76 hdf5_data_layer.cpp:80] Loading list of HDF5 filenames from: ./train_file_location.txt
I0807 16:12:04.248471    76 hdf5_data_layer.cpp:94] Number of HDF5 files: 1
I0807 16:12:04.276413    76 hdf5.cpp:32] Datatype class: H5T_FLOAT
I0807 16:12:04.485430    76 hdf5.cpp:35] Datatype class: H5T_INTEGER
I0807 16:12:04.486234    76 net.cpp:122] Setting up mnist
I0807 16:12:04.486274    76 net.cpp:129] Top shape: 100 1 28 28 (78400)
I0807 16:12:04.486292    76 net.cpp:129] Top shape: 100 1 1 1 (100)
I0807 16:12:04.486299    76 net.cpp:137] Memory required for data: 314000
I0807 16:12:04.486310    76 layer_factory.hpp:77] Creating layer conv1
I0807 16:12:04.486351    76 net.cpp:84] Creating Layer conv1
I0807 16:12:04.486377    76 net.cpp:406] conv1 <- data
I0807 16:12:04.486399    76 net.cpp:380] conv1 -> conv1
I0807 16:12:04.488049    76 net.cpp:122] Setting up conv1
I0807 16:12:04.488080    76 net.cpp:129] Top shape: 100 20 24 24 (1152000)
I0807 16:12:04.488085    76 net.cpp:137] Memory required for data: 4922000
I0807 16:12:04.488104    76 layer_factory.hpp:77] Creating layer pool1
I0807 16:12:04.488118    76 net.cpp:84] Creating Layer pool1
I0807 16:12:04.488167    76 net.cpp:406] pool1 <- conv1
I0807 16:12:04.488179    76 net.cpp:380] pool1 -> pool1
I0807 16:12:04.488214    76 net.cpp:122] Setting up pool1
I0807 16:12:04.488236    76 net.cpp:129] Top shape: 100 20 12 12 (288000)
I0807 16:12:04.488241    76 net.cpp:137] Memory required for data: 6074000
I0807 16:12:04.488258    76 layer_factory.hpp:77] Creating layer conv2
I0807 16:12:04.488272    76 net.cpp:84] Creating Layer conv2
I0807 16:12:04.488292    76 net.cpp:406] conv2 <- pool1
I0807 16:12:04.488301    76 net.cpp:380] conv2 -> conv2
I0807 16:12:04.488514    76 net.cpp:122] Setting up conv2
I0807 16:12:04.488549    76 net.cpp:129] Top shape: 100 50 8 8 (320000)
I0807 16:12:04.488559    76 net.cpp:137] Memory required for data: 7354000
I0807 16:12:04.488569    76 layer_factory.hpp:77] Creating layer pool2
I0807 16:12:04.488595    76 net.cpp:84] Creating Layer pool2
I0807 16:12:04.488600    76 net.cpp:406] pool2 <- conv2
I0807 16:12:04.488608    76 net.cpp:380] pool2 -> pool2
I0807 16:12:04.488617    76 net.cpp:122] Setting up pool2
I0807 16:12:04.488637    76 net.cpp:129] Top shape: 100 50 4 4 (80000)
I0807 16:12:04.488642    76 net.cpp:137] Memory required for data: 7674000
I0807 16:12:04.488647    76 layer_factory.hpp:77] Creating layer ip1
I0807 16:12:04.488687    76 net.cpp:84] Creating Layer ip1
I0807 16:12:04.488711    76 net.cpp:406] ip1 <- pool2
I0807 16:12:04.488720    76 net.cpp:380] ip1 -> ip1
I0807 16:12:04.491019    76 net.cpp:122] Setting up ip1
I0807 16:12:04.491047    76 net.cpp:129] Top shape: 100 500 (50000)
I0807 16:12:04.491052    76 net.cpp:137] Memory required for data: 7874000
I0807 16:12:04.491063    76 layer_factory.hpp:77] Creating layer relu1
I0807 16:12:04.491073    76 net.cpp:84] Creating Layer relu1
I0807 16:12:04.491078    76 net.cpp:406] relu1 <- ip1
I0807 16:12:04.491084    76 net.cpp:367] relu1 -> ip1 (in-place)
I0807 16:12:04.491093    76 net.cpp:122] Setting up relu1
I0807 16:12:04.491099    76 net.cpp:129] Top shape: 100 500 (50000)
I0807 16:12:04.491104    76 net.cpp:137] Memory required for data: 8074000
I0807 16:12:04.491108    76 layer_factory.hpp:77] Creating layer ip2
I0807 16:12:04.491116    76 net.cpp:84] Creating Layer ip2
I0807 16:12:04.491120    76 net.cpp:406] ip2 <- ip1
I0807 16:12:04.491128    76 net.cpp:380] ip2 -> ip2
I0807 16:12:04.491173    76 net.cpp:122] Setting up ip2
I0807 16:12:04.491195    76 net.cpp:129] Top shape: 100 10 (1000)
I0807 16:12:04.491201    76 net.cpp:137] Memory required for data: 8078000
I0807 16:12:04.491225    76 layer_factory.hpp:77] Creating layer loss
I0807 16:12:04.491238    76 net.cpp:84] Creating Layer loss
I0807 16:12:04.491257    76 net.cpp:406] loss <- ip2
I0807 16:12:04.491264    76 net.cpp:406] loss <- label
I0807 16:12:04.491284    76 net.cpp:380] loss -> loss
I0807 16:12:04.491363    76 layer_factory.hpp:77] Creating layer loss
I0807 16:12:04.491410    76 net.cpp:122] Setting up loss
I0807 16:12:04.491436    76 net.cpp:129] Top shape: (1)
I0807 16:12:04.491454    76 net.cpp:132]     with loss weight 1
I0807 16:12:04.491513    76 net.cpp:137] Memory required for data: 8078004
I0807 16:12:04.491520    76 net.cpp:198] loss needs backward computation.
I0807 16:12:04.491545    76 net.cpp:198] ip2 needs backward computation.
I0807 16:12:04.491551    76 net.cpp:198] relu1 needs backward computation.
I0807 16:12:04.491567    76 net.cpp:198] ip1 needs backward computation.
I0807 16:12:04.491572    76 net.cpp:198] pool2 needs backward computation.
I0807 16:12:04.491590    76 net.cpp:198] conv2 needs backward computation.
I0807 16:12:04.491595    76 net.cpp:198] pool1 needs backward computation.
I0807 16:12:04.491611    76 net.cpp:198] conv1 needs backward computation.
I0807 16:12:04.491616    76 net.cpp:200] mnist does not need backward computation.
I0807 16:12:04.491632    76 net.cpp:242] This network produces output loss
I0807 16:12:04.491647    76 net.cpp:255] Network initialization done.
I0807 16:12:04.491811    76 solver.cpp:172] Creating test net (#0) specified by net file: ./train_val.prototxt
I0807 16:12:04.491849    76 net.cpp:294] The NetState phase (1) differed from the phase (0) specified by a rule in layer mnist
I0807 16:12:04.491964    76 net.cpp:51] Initializing net from parameters: 
name: "LeNet"
state {
  phase: TEST
}
layer {
  name: "mnist"
  type: "HDF5Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  hdf5_data_param {
    source: "./test_file_location.txt"
    batch_size: 100
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 20
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 50
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "ip1"
  type: "InnerProduct"
  bottom: "pool2"
  top: "ip1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 500
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "ip1"
  top: "ip1"
}
layer {
  name: "ip2"
  type: "InnerProduct"
  bottom: "ip1"
  top: "ip2"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  inner_product_param {
    num_output: 10
    weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "ip2"
  bottom: "label"
  top: "accuracy"
  include {
    phase: TEST
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "ip2"
  bottom: "label"
  top: "loss"
}
I0807 16:12:04.492147    76 layer_factory.hpp:77] Creating layer mnist
I0807 16:12:04.492173    76 net.cpp:84] Creating Layer mnist
I0807 16:12:04.492180    76 net.cpp:380] mnist -> data
I0807 16:12:04.492200    76 net.cpp:380] mnist -> label
I0807 16:12:04.492221    76 hdf5_data_layer.cpp:80] Loading list of HDF5 filenames from: ./test_file_location.txt
I0807 16:12:04.492708    76 hdf5_data_layer.cpp:94] Number of HDF5 files: 1
I0807 16:12:04.523490    76 net.cpp:122] Setting up mnist
I0807 16:12:04.523555    76 net.cpp:129] Top shape: 100 28 28 1 (78400)
I0807 16:12:04.523562    76 net.cpp:129] Top shape: 100 1 1 1 (100)
I0807 16:12:04.523566    76 net.cpp:137] Memory required for data: 314000
I0807 16:12:04.523574    76 layer_factory.hpp:77] Creating layer label_mnist_1_split
I0807 16:12:04.523588    76 net.cpp:84] Creating Layer label_mnist_1_split
I0807 16:12:04.523596    76 net.cpp:406] label_mnist_1_split <- label
I0807 16:12:04.523603    76 net.cpp:380] label_mnist_1_split -> label_mnist_1_split_0
I0807 16:12:04.523614    76 net.cpp:380] label_mnist_1_split -> label_mnist_1_split_1
I0807 16:12:04.523640    76 net.cpp:122] Setting up label_mnist_1_split
I0807 16:12:04.523664    76 net.cpp:129] Top shape: 100 1 1 1 (100)
I0807 16:12:04.523686    76 net.cpp:129] Top shape: 100 1 1 1 (100)
I0807 16:12:04.523705    76 net.cpp:137] Memory required for data: 314800
I0807 16:12:04.523712    76 layer_factory.hpp:77] Creating layer conv1
I0807 16:12:04.523742    76 net.cpp:84] Creating Layer conv1
I0807 16:12:04.523761    76 net.cpp:406] conv1 <- data
I0807 16:12:04.523774    76 net.cpp:380] conv1 -> conv1
F0807 16:12:04.523913    76 blob.cpp:32] Check failed: shape[i] >= 0 (-3 vs. 0) 
*** Check failure stack trace: ***

I am running in CPU. Could someone provide some guidance?

Thanks

**Comment by Prakashvanapalli** [comment]
First you need to download and convert data into h5py file. see notebooks/mnist_caffe_model.ipynb
before running the train_solver.prototxt file.

**Comment by ldjpr** [comment]
That is not the issue. I ran all the previous steps before all successfully:

1. Install tensor and keras
2. Import
3. Downloading data
4. Converting data into hd5 format

Still when run the train solver I get the above mentioned error.

Please advice

Thanks

**Comment by Prakashvanapalli** [comment]
```
I0807 16:12:04.523555 76 net.cpp:129] Top shape: 100 28 28 1 (78400)
I0807 16:12:04.523562 76 net.cpp:129] Top shape: 100 1 1 1 (100)
```

For some reason, caffe needs evaluation data in a different format. If you carefully see my notebook, the following lines will be present 

```
## Downloading data 
img_rows, img_cols = 28, 28

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
```

x_train and x_test shapes are different. 

Thank you.

**Comment by ldjpr** [comment]
Hi

I appreciate you reply, but unfortunately I don't understand what you are trying to communicate me. 

Could you be more specific of what I should change?

Thanks for your help.

**Comment by Prakashvanapalli** [comment]
Please upload the code you have written. the code provided here should work if you are using docker.

**Comment by ldjpr** [comment]
Hi

I am using the Docker image. The code is the one in the notebook.

Dockerfile

`# This is the docker image available. I am using cpu version here. If needed there is gpu version available.
# run -p 8887:8888 -v ~/folder/notebooks:/model1/notebooks -v ~/folder/data:/model1/data -d caffe

FROM bvlc/caffe:cpu

# Copy the file into docker
COPY requirements.txt requirements.txt

# Run the copied file
RUN pip install -r requirements.txt

# create a folder called model1 and copy all the files in the folder into that folder
ADD . /model1

# Make model1 your work directory
WORKDIR /model1

# Create volumes (folders). one (data) to store data and the other(notebooks) to save your code.
VOLUME ["/model1/data", "/model1/notebooks"]

#copy notebooks
COPY notebooks/ /model1/notebooks/


# Expose your port 8888
EXPOSE 8888

# Run the following command to give a token(password) to your jupyter notebook.
CMD jupyter notebook --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='demo'`

Notebook code:

`!pip install tensorflow 
!pip install keras

import keras
from keras.datasets import mnist
import h5py

## Downloading data 
img_rows, img_cols = 28, 28

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

## Saving data in h5py format. 
with h5py.File('../data/train.h5', 'w') as f:
    f['data'] = x_train / 255.0
    f['label'] = y_train.reshape(-1, 1, 1, 1)

with h5py.File('../data/test.h5', 'w') as f:
   f['data'] = x_test / 255.0
   f['label'] = y_test.reshape(-1, 1, 1, 1)

f = h5py.File("../data/train.h5", "r")
print("train_data", f["data"][:].shape, f["label"][:].shape)
f.close()


f = h5py.File("../data/test.h5", "r")
print("test_data", f["data"][:].shape, f["label"][:].shape)
f.close()

## Run the caffe model using commandline . 
check 
- train_val.prototxt for model architecture code 
- train_solver.prototxt for model params 

Since I am using CPU, this will take time to run. 

!caffe train --solver=./train_solver.prototxt

## Important things to know.
- when defining params in train_solver.prototxt, I have mentioned snapshot as 5000. this means there will be a weight file saved after every 5000 iterations. You need to check the logs of where the model has high validation accuracy and use it for deploying the model

import glob
glob.glob("./snapshot/*")

import caffe 

# Define the location of model and weights 
model = "./deploy.prototxt"
weights = "./snapshot/lenet_mnist_iter_2970.caffemodel"

# start the classifier
net = caffe.Classifier(model, weights)

## load the test file 
f = h5py.File("../data/test.h5", "r")
print("test_data", f["data"][:].shape, f["label"][:].shape)

# Seperate the input and label data. 
data = f["data"][:]
actual_label = f["label"][:]

# reshape and print the actual label 
y_test = actual_label.reshape(-1)
print(y_test)

pred = net.predict(data)
print(pred.shape)

import numpy as np
y_pred = np.argmax(pred, axis =1)
print(y_pred)

from sklearn.metrics import accuracy_score
print("Accuracy: " + str(accuracy_score(y_pred=y_pred, y_true=y_test)))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_true=y_test, y_pred=y_pred))`

**Comment by snapfinger** [comment]
@ldjpr I encountered exactly same problem as yours. 

The code needs to be fixed is the one to reshape test data. After changing it to
```x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)```
the training went smoothly.

The author of this repo messed it up with 
```x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)```

Clearly he didn't execute the cells in sequence, but did modifications to the front cells after running the caffe training, and somehow changed to a wrong dimension without even realizing it.

**Comment by Prakashvanapalli** [comment]
Thanks for helping out .. I will soon update it in the code.

**Comment by ldjpr** [comment]
Thanks @snapfinger. These are great news. I will update in the the days. This is great.
